# Generated by Django 4.2.23 on 2025-09-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
                ('validation_type', models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('phone', 'Phone'), ('regex', 'Custom Regex'), ('conditional', 'Conditional')], default='none', max_length=20)),
                ('validation_rule', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('conditional_logic', models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_app.form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
